### PR TITLE
start modernization

### PR DESCRIPTION
**Pull request by WalternativE**
*switches to sdk based project format
*switches standard nuget client to paket
*enables restore via dotnet cli
*fixes api change in worldbank type provider call
*updates fsharp.data
*adapts path in fsx file to versionless path created by paket

### CODE REVIEW

**Comment by panesofglass** [comment]
Thank you for starting this modernization project!

**Comment by WalternativE** [comment]
You are welcome! Would you need additional commits to merge this PR? I tested it on two different machines (played through the whole Dojo) and it appeared to work well (both a recent Win10 though with VS and VS Code).

**Comment by panesofglass** [comment]
No, I was just waiting for your signal that it was ready. The commit above indicated this was a start. I'll take a look and merge.

**Comment by WalternativE** [comment]
Oh, sorry - when I wrote the commit I assumed there would be more to do ^^'

**Comment by panesofglass** [comment]
Thanks!

**Pull request merged**
